### ISSUE TITLE
Flowing texture 

### ISSUE THREAD

**Issue by CaptainBoggle** [Noahkiq/minecraft-randomiser#3]
After randomising textures twice, lava (and possibly water) still don’t seem to change texture in their non source block states. A fix for this would be great. Thanks.

**Comment by qixils** [comment]
this is due to the program's safe method of randomisation which only randomises textures of the same dimensions to avoid crashes. i can attempt to fix this but it may make the game less stable unless i do some very hacky solutions.

**Comment by qixils** [comment]
yeah this isn't going to be possible without adding a new randomisation mode entirely which would actually have less randomisation (to avoid crashing the game)

**Comment by CaptainBoggle** [comment]
Hmm. I found this similar program that has less features , but manages to fix the liquids problem. Maybe try looking in the source code and reverse engineer it. https://github.com/hyblocker/minecraftrandomiser/

**Comment by qixils** [comment]
the source code isn't actually provided there but i'm pretty sure i know how he does it.

my code only randomises textures with the exact some resolution, or number of pixels, so that everything from particle effects to item to UI elements can be safely randomised without any hassle. his code randomises by type of texture, ie block or item, and has no safety checks for if textures are the same dimensions. i could combine my method with his but it would remove the global pool of random textures and would result in less textures being randomised overall, which brings us back to square one.

there's no perfect solution to this problem of "max randomisation" unless specific hacks are added for lava, which would be very tedious and would prevent this from working with non-vanilla resource packs, which is functionality that i don't want to break.

**Comment by qixils** [comment]
add `--alttextures` when running resource_randomiser.py to use the alternative method; may cause crashes due to some of the textures that get randomised, i'll need to disable those (lmk if it happens)
